version: 2.1


jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./mvnw
      - run: ./mvnw -Dmaven.test.skip=true package
      - persist_to_workspace:
         root: ./
         paths:
           - target/
           

  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run:
          name: chmod permissions
          command: chmod +x ./mvnw
      - run: ./mvnw test
orbs: 
  jira: circleci/jira@1.3.1

workflows:
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
          post-steps:
            - jira/notify
             